### PR TITLE
Make credit maximum variable

### LINKED ISSUE #268: Make credit maximum variable
For the HSS module, it is important to make the upper credit bound variable, since users who are in the IGH only have a limit of 21GiB.

It may be that some changes outside `model/hss` have to be made (e.g. `sipa.graph_utils`), since I believe 63GiB are somewhat hard coded.

### PR DESCRIPTION
**Pull request by BelphegorPrime**
You're opening a pull request? __Awesome!__

Please make sure though you did the following (tick off everything you
already did):

- [ ] Run the tests and see them pass
- [ ] Rebase your branch on top of `develop`
- [ ] Include tests for features you introduced / bugs you fixed

This issue fixes #268

### CODE REVIEW

**Comment by BelphegorPrime** [comment]
added the one real name commit to that PR

**Comment by lukasjuhrich** [comment]
@BelphegorPrime Please undo the merge from develop into this branch (`git reset --hard HEAD^`), and rebase it onto develop (`git rebase develop`). One commit will “fall out”, since I cherry-picked it (the name→realname fix), and it is already included in develop.

Current graph:
```
6f865aa *   origin/develop origin/HEAD develop Merge pull request #285 from lukasjuhrich/frontend_tests
        |\  
cf29a89 | * lukas/frontend_tests frontend_tests Test `/bustimes` reachability
de208d0 | * Add last missing `generic` frontend tests
3fb8071 | * Add missing template
4ae1dbd | * Extend `generic` frontend tests
5100888 | * changed name to real realname
e3d1ada | * Add simple tests for `generic` and `usersuite`
        |/  
3be249c | *   marcel/develop Merge branch 'develop' into develop
        | |\  
        | |/  
        |/|   
24b2243 * |   Merge pull request #283 from lukasjuhrich/gerok_200
        |\ \  
5b5e026 | * | lukas/gerok_200 Fix PEP8
f7ad2f8 | * | Add test for unknown status logging
7c10c44 | * | Gerok: Don't raise on != 200 status codes
        |/ /  
92b68f3 | * pep8 adjusted
ceb6c7b | * changed name to real realname
8fcc6bd | * doc change
adf6a2a | * changed the property to variables
b771388 | * marcel/sipa-268 max_credit is now as an separate parameter added to the graph generation function
c061520 | * WIP added max_credit and daily_credit to the other user models
0c55899 | * WIP maybe max_credit and daily_credit stuff
        |/  
```

The reset undo's the unnecessary merge on top of `marcel/develop`, and the rebase will “move” the branches starting point from that lower commit to the current state of `develop`.

**Comment by lukasjuhrich** [comment]
By the way, your git can display nice graphs as well if you pass some parameters to `log`:

`git log --oneline --graph --decorate --all`

You can make an alias out of it like `git config alias.tree='git log […]'`, so you can just type `git tree`.

**Comment by lukasjuhrich** [comment]
Hey, since I wanted to deploy, I rebased your changes on top of develop. They now are on https://github.com/agdsn/sipa/tree/marcel_develop. I resolved the merge conflicts. You just have to hard reset your branch (assuming you made no further changes) to origin/marcel_develop.

**Comment by lukasjuhrich** [comment]
Closing, replaced by #287

**Pull request closed without merging**
