### PR TITLE
Allow userdb management with pycroft backend

### PR DESCRIPTION
**Pull request by Georgeto**
Mostly copied from the old wu model...

### CODE REVIEW

**Comment by lukasjuhrich** [comment]
Well, since there isn't really a functionality change, and the userdb isn't really testable, I propose testing in production on Tuesday after the services meeting.

**Comment by Georgeto** [comment]
> Well, since there isn't really a functionality change, and the userdb isn't really testable, I propose testing in production on Tuesday after the services meeting.

Well, in fact the change is already in production for more than a month... :D

**Comment by lukasjuhrich** [comment]
@Georgeto how does that work when this pull request has never been merged?

**Comment by Georgeto** [comment]
Just checkout the branch the pull request is on. The change was urgently needed (support ticket), therefore I didn't wait until the pull request was merged. Over time I forgot about this pull request.

**Pull request merged**
