### PR TITLE
Fix Issue #343 "Insert correct language attribute in `html` tag"

### LINKED ISSUE #343: Insert correct language attribute in `html` tag
While investigating #342 I noticed that SIPA always replies with
`<html lang="de" xmlns="http://www.w3.org/1999/html">`
no matter which language is actually used.

How to reproduce:
`curl --header "Accept-Language: en" https://agdsn.de/sipa/news/`

### PR DESCRIPTION
**Pull request by aekazitt**
You're opening a pull request? __Awesome!__

Please make sure though you did the following (tick off everything you
already did):

- [x] Run the tests and see them pass
- [x] Rebase your branch on top of `develop`
- [ ] Include tests for features you introduced / bugs you fixed

This issue fixes #343

### CODE REVIEW

**Comment by sebschrader** [comment]
Hi, thanks for working on #343.

Any reason for not using [`negotiate_locale`](http://babel.pocoo.org/en/latest/api/core.html#babel.core.negotiate_locale) or [`Locale.negotiate`](http://babel.pocoo.org/en/latest/api/core.html#babel.core.Locale.negotiate) from Babel? The first one returns a just the matched locale string and the second a `Locale` object. Those functions do already do all the work and are probably (more) correct.

It can be used in a [`localeselector`](https://pythonhosted.org/Flask-Babel/#flask.ext.babel.Babel.localeselector) from `Flask-Babel` as follows:

```python
@babel.localeselector
def get_current_locale():
    return negotiate_locale(request.accept_languages.values(), ['de', 'en'], sep='-')
```

Instead of returning `matched_locale`, the result of [`get_locale`](https://pythonhosted.org/Flask-Babel/#flask.ext.babel.get_locale) should be passed to the template and used, because it reflects the language we're actually using. A user might explicitly use a different language, then the one we've derived from the `Accept-Language` header. Our locale selector already handles this and prefers a locale stored in the session over the one derived from the `Accept-Language` header.

The `localeselector` of sipa is defined in `sipa/base.py`. Mabe @lukasjuhrich knows why it isn't defined in `sipa/babel.py`. Maybe there is no real reason and it can be moved to `babel.py` or the other way round.

**Comment by aekazitt** [comment]
@sebschrader 
Thanks for the response. I merely worked off of the functions available in ```babel.py``` and found that a ```localeselector``` wasn't implemented there nor what the default language returned should be. 

Secondly I found that the ```babel.local_preferences``` function has a weird behavior as to injecting ````'en'``` Locale prior to ```request.accept_languages``` thus if I pull results from locale_preferences to run through possible_locale, the first locale matched will always be English.

I can make changes like you mentioned above if you want me to rework my solution. My goal was to change as few files as possible due to not knowing the system.

**Comment by sebschrader** [comment]
> Secondly I found that the `babel.local_preferences` function has a weird behavior as to injecting `'en'` Locale prior to `request.accept_languages` thus if I pull results from `locale_preferences` to run through `possible_locale`, the first locale matched will always be English.

Yup, you're right, `locale_preferences` is a bit weird. Besides, it is only used once and `negotiate_locale` can be used for this case as well. I removed the function and replaced it with `negotiate_locale` in #345. You can do the changes we discussed and move the `localeselector` to `babel.py`, you can ignore my PR #345 it should not interfere with yours.

**Comment by lukasjuhrich** [comment]
I would suggest using `negotiate_locale` as well.
@sebschrader there is no real reason for the selector to be defined in `base.py` instead of `babel.py`. I have to confess the project structure is a bit inconsistent.

**Pull request closed without merging**
