### PR TITLE
Fix #97, display version information.

### LINKED ISSUE #97: Display version of SIPA
Since SIPA is still changing rapidly and there is no fixed release cycle, it would be much easier for debugging etc. if SIPA displayed some kind of version, e.g. the hash of the latest commit it's based on.

Maybe it could even link to that commit on Github.

### PR DESCRIPTION
**Pull request by toothstone**
Add /version, which displays the 20 latest commits of the branch
sipa is running on. I've not included translations since all
git information will be in English anyhow.
This means .git has to be added to the docker image.

### CODE REVIEW

**Comment by lukasjuhrich** [comment]
Including `.git` in the working directory of the build image is not an option. What it is used for is information about the current branch and few past commits, which does not require every complete state of the project back one year. `.git` uses even more space than the whole code for sipa alltogether.

One has to find a possibility to include this information at build time, although a quick search did not offer any possibilities offered by docker directly (like a bootstrap-script or something).

Thanks for the groundwork tho, @toothstone !

**Comment by toothstone** [comment]
I don't really see your point here. /.git currently takes up 3.4 MB, which is - to say the least - neglectible. The SIPA image takes up 750 MB alone, and on top comes the ever growing /content.

**Comment by toothstone** [comment]
To also reply something positive: Including .git in the image allows imho greater flexibility and - most important - makes sure that the currently running state is displayed.

**Comment by lukasjuhrich** [comment]
The point is that you are including _way_ too much information in regard of what you actually need. It would be like dragging the Eiffel tower to your home instead of just taking a photo proving you were there.

To get onto your last two arguments: “Greater flexibility” – there is nothing we need out of this `.git` directory but what is concerned here. Adding a huge multiple of what you need just as a placeholder is never a good idea.

The last thing you say is “well, it fixes it”. Yes, it does, but: “there must be a better way!”.

I just stick to the fact that a feature should _never_ require the whole `.git` directory to be accessible in production in order to work. Only the needed (static) information should be given.

**Comment by toothstone** [comment]
What I don't like about any Docker-based solution is that we would have to generate parts of SIPA outside  of it, breaking the so far quite consistent flow of information.

**Comment by lukasjuhrich** [comment]
I do not consider a custom build process “outside” of SIPA, although it wouldn't be part of a Dockerfile.

Could you explain how this would break the “consistent flow of information”? After running such a script (and building the image), all the necessary, static information (such as the version information) has been “burned” into the docker image, making sipa stateless. Feeding it with environment variables, you can adapt sipa to its production environment, and automatically fetch the variable content from outside the container. This does not sound inconsistent to me.

**Comment by mmarx** [comment]
Just have a post-{commit,merge,checkout} hook write the needed information into a git-ignored file, and include that file in the docker image (failing the build process if it's not there).

**Comment by lukasjuhrich** [comment]
@mmarx the problem being that we _do not have a building infrastructure_. Images are being built locally, i.e. by me. Thus, hooks do not work, since they would have to be replicated at each clone to verify integrity. Also, one cannot really abort a docker build if some statement is “False”.

**Comment by mmarx** [comment]
What happens when the RUN command exits with non-zero exit status?

**Comment by lukasjuhrich** [comment]
@mmarx 

…

Nevermind.

**Comment by lukasjuhrich** [comment]
@toothstone After our private conversation I will merge this pull request adding a few UI improvements and a translation.

**Comment by toothstone** [comment]
Sure, thanks!

**Pull request merged**
